### ISSUE TITLE
Cant register in mcbans site

### ISSUE THREAD

**Issue by subarualpha** [MCBans/MCBans#114]
I was trying to get a MCBans plugin and put in my server plugin file
But yesterday Google said "MCbans.com is not secured" so I just waited until mcbans secured
and then I tried to make my account in mcbans but it always said "that username is already used" and then I just try to check who is using my username
but no one was using it. How do I register?
![mcbans1](https://user-images.githubusercontent.com/90103087/141597572-146e723c-afd4-4264-8cab-d542edefceaa.png)
![mcbans2](https://user-images.githubusercontent.com/90103087/141597585-b7fce3a8-232e-4ecc-a3fc-f8fbc9a2ede2.png)

**Comment by CorporalDecay** [comment]
@subarualpha As far as I know, the MCBans project has been abandoned and has not received an update in years. I'd recommend going with MCBouncer which is the next best thing to MCBans or Litebans (paid plugin).
