### ISSUE TITLE
MCBans API DOWN???

### ISSUE THREAD

**Issue by Geckomacabre** [MCBans/MCBans#119]
when adding a ban using mcbans 5.1 i am met with this message : ! [Wed 00:50:34 WARN  Minecraft] [MCBans] Error occurred with local banning. Please report this to an MCBans developer.
  [Wed 00:50:35 INFO ] [MCBans]  MCBans API is down or unreachable. Offline ban added!
  
  Ive tried this before at peak hours as well with the same problem any help?
![mcbans](https://user-images.githubusercontent.com/91030858/199404307-e99970cb-905b-4a5b-94da-24490488593a.PNG)

**Comment by firestar** [comment]
Thank you for the report, this has been resolved
