### ISSUE TITLE
Add Customizable Language Files

### ISSUE THREAD

**Issue by Rmarmorstein** [MCBans/MCBans#83]
MCBans, as far as I am aware, does not allow changing the colors, formatting, etc. of messages, unless you hack into the plugin. 

Proposal: Add a Language file (or section in the config) where you can edit the colors, and content of messages. 

I know this would be helpful to me, and I'm sure lots of other server administrators.

**Comment by firestar** [comment]
we actually do have language files, the the plugins/mcbans/languages/ folder, then you point the config setting "language:" to the files name.
