### ISSUE TITLE
Stephenblong issue

### ISSUE THREAD

**Issue by connection-lost** [MCBans/MCBans#92]
It's been a long time since this issue happens.

Whenever a server issued a ban, with an invalid name, that never joined MCbans server before, the banned player name will become Stephenblong.
Upon a new player connecting to the server, the server will sometimes (turns out to be if API server cannot response fast enough), will think that player is stephenblong, thus kicking the player.
Sometimes, admins may make a typo, sometimes, the banned player changed his name before an admin bans him. These are two ways to run into this issue. The banning message is shown as normal, making it difficult for admins to realize they had done wrong.

The current fix is to constantly unban stephenblong in case someone issued a typoed ban. It is not good.

**Comment by connection-lost** [comment]
I am not able to reproduce this issue again, since I am running out of alt accounts.
Only those are new to mcbans server will be affected.

**Comment by Searchndstroy** [comment]
I can confirm that this is possible, but I do not have alternate accounts to test this with.

It does not look like MCBans is well-prepared for UUIDs.


Fetching player information (such as bans) on the MCBans servers still uses a username, not a UUID.
See PlayerListener line number 77.

Banning players through /ban <playername> will send the username, not the UUID.
See BaseCommand at line 97, does not set the target's UUID (I don't know why it's commented out, maybe it caused issues??).


If you have any more alternate accounts, try logging onto a test server with mcbans, change your username and wait for a period of time (probably about 10-15 mins) and then ban the account. I am genuinely interesting to see the result.
