### ISSUE TITLE
Biggest BS i've ever seen

### ISSUE THREAD

**Issue by Bluscream** [MCBans/MCBans#94]
When you join a server it just says "you dont have enough rep" no info or links at all.

When you google that you get to MCBans

On MCbans website no way to lookup your "infranctions" / reputation

When trying to register on the forum:
```
MCBans Community - Error
Some of your information (email address, username, etc) has been found in the Stop Forum Spam database. You are currently not allowed to Register here. If you believe this was not correct, please reply or use the contact form http://forums.mcbans.com/support-tickets/open
```
The funny thing about that is that the ticket system requires you to be logged onto the forum...

So all in all just BS and wasted 4 hours of my time.

**Comment by firestar** [comment]
Turn off your vpn or connect to another server in your vpn network. this is pretty clearly an issue on your end.

you can easily look up global bans by going to http://mcbans.com/player/<yourname>

**Comment by Bluscream** [comment]
Im not even using a vpn

**Comment by Bluscream** [comment]
Also i suppose my vpn is blocking the search field on the website you posted ....

**Comment by firestar** [comment]
there is not a search field, why would you need to search for your own name? http://mcbans.com/player/<playername> although not stated is quite implied.

**Comment by Bluscream** [comment]
Okay so how am i supposed to find my details without any search functionality?

**Comment by Bluscream** [comment]
Am i supposed to ctrl+f 197 pages?

**Comment by firestar** [comment]
http://mcbans.com/player/playername

**Comment by Bluscream** [comment]
Okay i got two bans, what now?
